sudo: required
services:
  - docker

before_install:
  - docker build -t vladsadretdinov/docker-react -f Dockerfile.dev .

script:
  - docker run vladsadretdinov/docker-react npm run test -- --coverage